"""
pdf_generator.py
================

Company Research Assistant - PDF Report Generation Module.

This module is responsible for turning aggregated, AI-analyzed company
research data into a clean, professional PDF report using ReportLab.

Responsibilities:
    * Building a multi-section business report: title, company info,
      summary, products/services, pain points, and a competitor table.
    * Automatic page breaks and word wrapping via ReportLab's Platypus
      flowable layout engine.
    * Consistent footer on every page ("Generated by AI Company Research
      Assistant" + current date).
    * Saving the PDF into a `reports/` directory (auto-created if
      missing), with a filename of the form:
          <company_name>_<YYYY-MM-DD>_<HHMMSS>.pdf

This module contains NO user interface code. It is intended to be
imported and used by higher-level application layers (e.g. app.py),
typically after search.py, crawler.py, and ai.py have produced the
company's research data.

Example
-------
    from pdf_generator import create_pdf

    company_data = {
        "company_name": "Tesla",
        "website": "https://tesla.com",
        "phone": "+1-512-516-8177",
        "address": "1 Tesla Road, Austin, TX",
        "summary": "Tesla designs and manufactures electric vehicles...",
        "products": ["Model 3", "Model Y", "Solar Roof"],
        "services": ["Supercharger network", "Vehicle insurance"],
        "pain_points": ["Supply chain constraints", "Price competition"],
        "competitors": [
            {"name": "Rivian", "website": "https://rivian.com"},
            {"name": "Ford", "website": "https://ford.com"},
        ],
    }

    pdf_path = create_pdf(company_data)
    print(f"Report saved to: {pdf_path}")
"""

from __future__ import annotations

import logging
import os
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    ListFlowable,
    ListItem,
    PageBreak,
    PageTemplate,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# --------------------------------------------------------------------------
# Constants
# --------------------------------------------------------------------------

REPORTS_DIRECTORY: str = "reports"

PAGE_SIZE = letter
PAGE_MARGIN_INCHES: float = 0.75
FOOTER_TEXT_LEFT: str = "Generated by AI Company Research Assistant"

DEFAULT_SPACER_HEIGHT: float = 0.18 * inch
SECTION_SPACER_HEIGHT: float = 0.28 * inch

# Brand-ish color palette used for headings, tables, and rules.
COLOR_PRIMARY = colors.HexColor("#1F3A5F")
COLOR_ACCENT = colors.HexColor("#2E6E9E")
COLOR_TABLE_HEADER_BG = colors.HexColor("#1F3A5F")
COLOR_TABLE_HEADER_TEXT = colors.white
COLOR_TABLE_ROW_ALT_BG = colors.HexColor("#F2F5F8")
COLOR_MUTED_TEXT = colors.HexColor("#555555")

MAX_FILENAME_LENGTH: int = 80

# --------------------------------------------------------------------------
# Logging Configuration
# --------------------------------------------------------------------------

logger = logging.getLogger(__name__)
if not logger.handlers:
    _handler = logging.StreamHandler()
    _formatter = logging.Formatter(
        "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
    )
    _handler.setFormatter(_formatter)
    logger.addHandler(_handler)
logger.setLevel(logging.INFO)


# --------------------------------------------------------------------------
# Custom Exceptions
# --------------------------------------------------------------------------

class PDFGenerationError(Exception):
    """Raised when the PDF report could not be generated."""


# --------------------------------------------------------------------------
# Style Registry
# --------------------------------------------------------------------------

def _build_styles() -> Dict[str, ParagraphStyle]:
    """
    Build and return the full set of paragraph styles used throughout
    the report, layered on top of ReportLab's base sample stylesheet.

    Returns:
        A dictionary mapping style names to ParagraphStyle instances.
    """
    base = getSampleStyleSheet()

    styles: Dict[str, ParagraphStyle] = {
        "ReportTitle": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=26,
            leading=32,
            alignment=TA_CENTER,
            textColor=COLOR_PRIMARY,
            spaceAfter=6,
        ),
        "ReportSubtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base["Normal"],
            fontSize=11,
            leading=14,
            alignment=TA_CENTER,
            textColor=COLOR_MUTED_TEXT,
            spaceAfter=4,
        ),
        "SectionHeading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontSize=15,
            leading=18,
            spaceBefore=10,
            spaceAfter=8,
            textColor=COLOR_PRIMARY,
            borderPadding=0,
        ),
        "BodyText": ParagraphStyle(
            "BodyText",
            parent=base["Normal"],
            fontSize=10.5,
            leading=15,
            alignment=TA_LEFT,
            spaceAfter=6,
        ),
        "LabelText": ParagraphStyle(
            "LabelText",
            parent=base["Normal"],
            fontSize=10.5,
            leading=14,
            textColor=colors.black,
            spaceAfter=4,
        ),
        "BulletText": ParagraphStyle(
            "BulletText",
            parent=base["Normal"],
            fontSize=10.5,
            leading=14,
            spaceAfter=3,
        ),
        "TableCell": ParagraphStyle(
            "TableCell",
            parent=base["Normal"],
            fontSize=10,
            leading=13,
            textColor=colors.black,
        ),
        "TableHeaderCell": ParagraphStyle(
            "TableHeaderCell",
            parent=base["Normal"],
            fontSize=10.5,
            leading=13,
            textColor=COLOR_TABLE_HEADER_TEXT,
            fontName="Helvetica-Bold",
        ),
        "EmptyState": ParagraphStyle(
            "EmptyState",
            parent=base["Normal"],
            fontSize=10,
            leading=13,
            textColor=COLOR_MUTED_TEXT,
            spaceAfter=4,
        ),
    }
    return styles


# --------------------------------------------------------------------------
# Filesystem / Filename Helpers
# --------------------------------------------------------------------------

def _ensure_reports_directory(directory: str = REPORTS_DIRECTORY) -> str:
    """
    Ensure the reports output directory exists, creating it if necessary.

    Args:
        directory: The directory path to ensure exists.

    Returns:
        The (now guaranteed to exist) directory path.
    """
    if not os.path.isdir(directory):
        os.makedirs(directory, exist_ok=True)
        logger.info("Created reports directory: %s", directory)
    return directory


def _sanitize_company_name(company_name: str) -> str:
    """
    Sanitize a company name for safe use in a filename.

    Args:
        company_name: The raw company name.

    Returns:
        A filesystem-safe version of the company name (alphanumerics,
        underscores, and hyphens only), truncated to a reasonable length.
    """
    if not company_name:
        return "Unknown_Company"

    cleaned = re.sub(r"[^\w\s-]", "", company_name).strip()
    cleaned = re.sub(r"[\s]+", "_", cleaned)
    cleaned = cleaned.strip("_-") or "Unknown_Company"

    return cleaned[:MAX_FILENAME_LENGTH]


def _build_output_filepath(
    company_name: str, directory: str = REPORTS_DIRECTORY
) -> str:
    """
    Build the full output file path for a company's PDF report, in the
    format: <company_name>_<YYYY-MM-DD>_<HHMMSS>.pdf

    Args:
        company_name: The company's name, used to derive the filename.
        directory: The target directory for the generated PDF.

    Returns:
        The full file path where the PDF should be written.
    """
    safe_name = _sanitize_company_name(company_name)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    filename = f"{safe_name}_{timestamp}.pdf"
    return os.path.join(directory, filename)


# --------------------------------------------------------------------------
# Content Builder Helpers (Section Builders)
# --------------------------------------------------------------------------

def add_title(
    story: List[Any], styles: Dict[str, ParagraphStyle], company_name: str
) -> None:
    """
    Append a large, centered report title section to the story, showing
    the company name and the report generation date.

    Args:
        story: The ReportLab flowable list being built up.
        styles: The dictionary of paragraph styles to use.
        company_name: The name of the company being reported on.
    """
    generated_on = datetime.now().strftime("%B %d, %Y at %H:%M")

    story.append(Paragraph(f"{company_name}", styles["ReportTitle"]))
    story.append(Paragraph("Company Research Report", styles["ReportSubtitle"]))
    story.append(Paragraph(f"Generated on {generated_on}", styles["ReportSubtitle"]))
    story.append(Spacer(1, SECTION_SPACER_HEIGHT))


def add_company_information(
    story: List[Any], styles: Dict[str, ParagraphStyle], company_data: Dict[str, Any]
) -> None:
    """
    Append a company information section (name, website, phone, address)
    to the story, formatted as a clean two-column table.

    Args:
        story: The ReportLab flowable list being built up.
        styles: The dictionary of paragraph styles to use.
        company_data: The company's research data dictionary.
    """
    story.append(Paragraph("Company Information", styles["SectionHeading"]))

    rows = [
        ("Company Name", company_data.get("company_name") or "Not available"),
        ("Website", company_data.get("website") or "Not available"),
        ("Phone", company_data.get("phone") or "Not available"),
        ("Address", company_data.get("address") or "Not available"),
    ]

    table_data = [
        [
            Paragraph(f"<b>{label}</b>", styles["LabelText"]),
            Paragraph(str(value), styles["LabelText"]),
        ]
        for label, value in rows
    ]

    info_table = Table(
        table_data,
        colWidths=[1.6 * inch, 4.6 * inch],
        hAlign="LEFT",
    )
    info_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#DDDDDD")),
            ]
        )
    )

    story.append(info_table)
    story.append(Spacer(1, SECTION_SPACER_HEIGHT))


def add_company_summary(
    story: List[Any], styles: Dict[str, ParagraphStyle], summary: str
) -> None:
    """
    Append a professional summary paragraph section to the story.

    Args:
        story: The ReportLab flowable list being built up.
        styles: The dictionary of paragraph styles to use.
        summary: The company summary text (plain text, will be escaped).
    """
    story.append(Paragraph("Company Summary", styles["SectionHeading"]))

    if summary and summary.strip():
        story.append(Paragraph(_escape_text(summary.strip()), styles["BodyText"]))
    else:
        story.append(
            Paragraph("No summary information available.", styles["EmptyState"])
        )

    story.append(Spacer(1, SECTION_SPACER_HEIGHT))


def add_products_services(
    story: List[Any],
    styles: Dict[str, ParagraphStyle],
    products: List[str],
    services: List[str],
) -> None:
    """
    Append products and services sections to the story as bulleted lists.

    Args:
        story: The ReportLab flowable list being built up.
        styles: The dictionary of paragraph styles to use.
        products: A list of product name/description strings.
        services: A list of service name/description strings.
    """
    story.append(Paragraph("Products", styles["SectionHeading"]))
    _add_bulleted_list(story, styles, products, empty_message="No products identified.")
    story.append(Spacer(1, DEFAULT_SPACER_HEIGHT))

    story.append(Paragraph("Services", styles["SectionHeading"]))
    _add_bulleted_list(story, styles, services, empty_message="No services identified.")
    story.append(Spacer(1, SECTION_SPACER_HEIGHT))


def add_pain_points(
    story: List[Any], styles: Dict[str, ParagraphStyle], pain_points: List[str]
) -> None:
    """
    Append a bulleted list of business pain points to the story.

    Args:
        story: The ReportLab flowable list being built up.
        styles: The dictionary of paragraph styles to use.
        pain_points: A list of pain point strings.
    """
    story.append(Paragraph("Pain Points", styles["SectionHeading"]))
    _add_bulleted_list(
        story, styles, pain_points, empty_message="No pain points identified."
    )
    story.append(Spacer(1, SECTION_SPACER_HEIGHT))


def add_competitor_table(
    story: List[Any],
    styles: Dict[str, ParagraphStyle],
    competitors: List[Dict[str, str]],
) -> None:
    """
    Append a professionally formatted competitor table (Name / Website)
    to the story.

    Args:
        story: The ReportLab flowable list being built up.
        styles: The dictionary of paragraph styles to use.
        competitors: A list of dictionaries shaped as
            {"name": str, "website": str}.
    """
    story.append(Paragraph("Competitors", styles["SectionHeading"]))

    if not competitors:
        story.append(
            Paragraph("No competitors identified.", styles["EmptyState"])
        )
        story.append(Spacer(1, SECTION_SPACER_HEIGHT))
        return

    header_row = [
        Paragraph("Competitor Name", styles["TableHeaderCell"]),
        Paragraph("Website", styles["TableHeaderCell"]),
    ]
    table_data: List[List[Any]] = [header_row]

    for competitor in competitors:
        name = str(competitor.get("name", "") or "Not available")
        website = str(competitor.get("website", "") or "Not available")
        table_data.append(
            [
                Paragraph(_escape_text(name), styles["TableCell"]),
                Paragraph(_escape_text(website), styles["TableCell"]),
            ]
        )

    competitor_table = Table(
        table_data,
        colWidths=[2.8 * inch, 3.4 * inch],
        hAlign="LEFT",
        repeatRows=1,
    )

    table_style_commands = [
        ("BACKGROUND", (0, 0), (-1, 0), COLOR_TABLE_HEADER_BG),
        ("TEXTCOLOR", (0, 0), (-1, 0), COLOR_TABLE_HEADER_TEXT),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
    ]

    # Zebra-striped alternating row backgrounds for readability.
    for row_index in range(1, len(table_data)):
        if row_index % 2 == 0:
            table_style_commands.append(
                ("BACKGROUND", (0, row_index), (-1, row_index), COLOR_TABLE_ROW_ALT_BG)
            )

    competitor_table.setStyle(TableStyle(table_style_commands))

    story.append(competitor_table)
    story.append(Spacer(1, SECTION_SPACER_HEIGHT))


# --------------------------------------------------------------------------
# Internal Rendering Helpers
# --------------------------------------------------------------------------

def _escape_text(text: str) -> str:
    """
    Escape characters that have special meaning in ReportLab's minimal
    XML markup used inside Paragraph objects.

    Args:
        text: The raw text to escape.

    Returns:
        The escaped text, safe to embed in a Paragraph.
    """
    if not text:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _add_bulleted_list(
    story: List[Any],
    styles: Dict[str, ParagraphStyle],
    items: List[str],
    empty_message: str,
) -> None:
    """
    Append a bulleted (unordered) list of items to the story, or an
    empty-state message if no items are provided.

    Args:
        story: The ReportLab flowable list being built up.
        styles: The dictionary of paragraph styles to use.
        items: The list of string items to render as bullets.
        empty_message: Message to display when `items` is empty.
    """
    cleaned_items = [str(item).strip() for item in (items or []) if str(item).strip()]

    if not cleaned_items:
        story.append(Paragraph(empty_message, styles["EmptyState"]))
        return

    bullet_items = [
        ListItem(
            Paragraph(_escape_text(item), styles["BulletText"]),
            bulletColor=COLOR_ACCENT,
        )
        for item in cleaned_items
    ]

    story.append(
        ListFlowable(
            bullet_items,
            bulletType="bullet",
            start="circle",
            leftIndent=18,
            bulletFontSize=6,
        )
    )


def _footer_canvas(canvas_obj: Any, doc: Any) -> None:
    """
    Draw the page footer (generated-by text, current date, and page
    number) on every page of the document.

    Args:
        canvas_obj: The ReportLab canvas being drawn on for this page.
        doc: The document template instance (provides page geometry).
    """
    canvas_obj.saveState()

    footer_y = 0.5 * inch
    page_width = doc.pagesize[0]
    margin = doc.leftMargin

    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.setFillColor(COLOR_MUTED_TEXT)

    current_date_str = datetime.now().strftime("%Y-%m-%d")
    left_text = f"{FOOTER_TEXT_LEFT} | {current_date_str}"
    canvas_obj.drawString(margin, footer_y, left_text)

    page_number_text = f"Page {doc.page}"
    canvas_obj.drawRightString(page_width - margin, footer_y, page_number_text)

    canvas_obj.setStrokeColor(colors.HexColor("#DDDDDD"))
    canvas_obj.line(margin, footer_y + 12, page_width - margin, footer_y + 12)

    canvas_obj.restoreState()


# --------------------------------------------------------------------------
# Data Validation Helper
# --------------------------------------------------------------------------

def _normalize_company_data(company_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Normalize and validate the incoming company data dictionary, filling
    in safe defaults for any missing fields.

    Args:
        company_data: The raw company data dictionary provided by the caller.

    Returns:
        A normalized dictionary with all expected keys present and
        correctly typed.
    """
    normalized: Dict[str, Any] = {
        "company_name": str(company_data.get("company_name") or "Unknown Company").strip(),
        "website": str(company_data.get("website") or "").strip(),
        "phone": str(company_data.get("phone") or "").strip(),
        "address": str(company_data.get("address") or "").strip(),
        "summary": str(company_data.get("summary") or "").strip(),
        "products": list(company_data.get("products") or []),
        "services": list(company_data.get("services") or []),
        "pain_points": list(company_data.get("pain_points") or []),
        "competitors": [],
    }

    raw_competitors = company_data.get("competitors") or []
    for competitor in raw_competitors:
        if isinstance(competitor, dict):
            normalized["competitors"].append(
                {
                    "name": str(competitor.get("name", "")).strip(),
                    "website": str(competitor.get("website", "")).strip(),
                }
            )
        else:
            # Tolerate a plain string competitor entry gracefully.
            normalized["competitors"].append({"name": str(competitor), "website": ""})

    return normalized


# --------------------------------------------------------------------------
# Main Entry Point
# --------------------------------------------------------------------------

def create_pdf(
    company_data: Dict[str, Any],
    output_directory: str = REPORTS_DIRECTORY,
) -> str:
    """
    Generate a professional PDF company research report and save it to
    the reports directory.

    Args:
        company_data: A dictionary shaped as:
            {
                "company_name": str,
                "website": str,
                "phone": str,
                "address": str,
                "summary": str,
                "products": List[str],
                "services": List[str],
                "pain_points": List[str],
                "competitors": [{"name": str, "website": str}, ...],
            }
        output_directory: The directory in which to save the generated
            PDF (created automatically if it doesn't exist).

    Returns:
        The full file path of the generated PDF report.

    Raises:
        PDFGenerationError: If the PDF could not be generated for any
            reason (invalid data, filesystem errors, ReportLab failures).
    """
    if not isinstance(company_data, dict):
        raise PDFGenerationError("company_data must be a dictionary.")

    try:
        normalized_data = _normalize_company_data(company_data)
        directory = _ensure_reports_directory(output_directory)
        output_path = _build_output_filepath(normalized_data["company_name"], directory)

        logger.info(
            "Generating PDF report for %s at %s",
            normalized_data["company_name"],
            output_path,
        )

        styles = _build_styles()
        margin = PAGE_MARGIN_INCHES * inch

        doc = BaseDocTemplate(
            output_path,
            pagesize=PAGE_SIZE,
            leftMargin=margin,
            rightMargin=margin,
            topMargin=margin,
            bottomMargin=margin,
            title=f"{normalized_data['company_name']} - Company Research Report",
            author="AI Company Research Assistant",
        )

        frame = Frame(
            doc.leftMargin,
            doc.bottomMargin,
            doc.width,
            doc.height,
            id="main_frame",
        )
        template = PageTemplate(id="report_template", frames=[frame], onPage=_footer_canvas)
        doc.addPageTemplates([template])

        story: List[Any] = []

        add_title(story, styles, normalized_data["company_name"])
        add_company_information(story, styles, normalized_data)
        add_company_summary(story, styles, normalized_data["summary"])
        add_products_services(
            story, styles, normalized_data["products"], normalized_data["services"]
        )
        add_pain_points(story, styles, normalized_data["pain_points"])
        add_competitor_table(story, styles, normalized_data["competitors"])

        doc.build(story)

        logger.info("Successfully generated PDF report: %s", output_path)
        return output_path

    except PDFGenerationError:
        raise
    except OSError as exc:
        logger.error("Filesystem error while generating PDF: %s", exc)
        raise PDFGenerationError(f"Filesystem error while generating PDF: {exc}") from exc
    except Exception as exc:  # noqa: BLE001 - convert any ReportLab failure to a friendly error.
        logger.error("Unexpected error while generating PDF: %s", exc)
        raise PDFGenerationError(f"Failed to generate PDF report: {exc}") from exc


# --------------------------------------------------------------------------
# Module Self-Test (only runs when executed directly, not on import)
# --------------------------------------------------------------------------

if __name__ == "__main__":
    logging.getLogger(__name__).setLevel(logging.DEBUG)

    sample_company_data = {
        "company_name": "Tesla",
        "website": "https://tesla.com",
        "phone": "+1-512-516-8177",
        "address": "1 Tesla Road, Austin, TX 78725",
        "summary": (
            "Tesla, Inc. designs, manufactures, and sells electric vehicles, "
            "energy generation, and storage systems, aiming to accelerate "
            "the world's transition to sustainable energy."
        ),
        "products": ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
        "services": ["Supercharger network", "Vehicle insurance", "Tesla Energy"],
        "pain_points": [
            "Intense EV market competition",
            "Supply chain and battery material constraints",
            "Regulatory and tariff exposure across markets",
        ],
        "competitors": [
            {"name": "Rivian", "website": "https://rivian.com"},
            {"name": "Ford", "website": "https://ford.com"},
            {"name": "BYD", "website": "https://byd.com"},
        ],
    }

    generated_path = create_pdf(sample_company_data)
    print(f"PDF generated at: {generated_path}")